name: pykrack
channels:
  - conda-forge
  - fastai
dependencies:
  - python=3.10.*
  - pip
  - jupyter
  - notebook
  - fastai::nbdev
  - numpy
  - pandas
  - networkx
  - r-base
  - r-rmarkdown
  - r-sna
  - rpy2
  - twine #For package publishing
  - anaconda-client #For package publishing
  - conda-build #For package publishing
  - conda-verify #For package publishing
  # - pip:
    # - numpy
    # - pandas
    # - networkx
    # - scikit-learn
    # - scipy
    # - matplotlib
    # - descartes
    # - alphashape
    # - shapely
    # - plotly
    # - graphtools
    # - pygsp
