# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pyKrack',
                'doc_host': 'https://FerranC96.github.io',
                'git_url': 'https://github.com/FerranC96/pyKrack',
                'lib_path': 'pyKrack'},
  'syms': { 'pyKrack.core': {'pyKrack.core.foo': ('core.html#foo', 'pyKrack/core.py')},
            'pyKrack.krackhardt': { 'pyKrack.krackhardt.compute_hierarchy': ('krackhardt.html#compute_hierarchy', 'pyKrack/krackhardt.py'),
                                    'pyKrack.krackhardt.graph_properties': ('krackhardt.html#graph_properties', 'pyKrack/krackhardt.py')}}}
