# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['graph_properties']

# %% ../nbs/00_core.ipynb 3
def graph_properties(G):
    "Return the properties of a NetworkX graph"

    import networkx as nx #Be mindful of scoping!

    properties = f"Edges:{G.number_of_edges()}, Nodes:{G.number_of_nodes()}, Avg Degree:{sum(dict(G.degree()).values())/G.number_of_nodes()}, Density:{nx.density(G)}"

    return properties
